openapi: 3.0.0
info:
  title: Social Media API
  description: API for social media application
  version: 1.0.0

servers:
  - url: http://localhost:5001/api/v1

tags:
  - name: Authorization and Authentication
    description: Validation and Verification of users

paths:
  /auth/register:
    post:
      tags:
        - Authorization and Authentication
      summary: Register new user
      description: Create space for new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: Created, New user Created
          schema:
            type: object
            properties:
              name:
                type: string
              token:
                type: string
        '400':
          description: Bad Request, Insufficient Data
        '500':
          description: Internal Server Error
  
  /auth/login:
    post:
      tags:
        - Authorization and Authentication
      summary: Login User
      description: Login the previous user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Login the user
        '400':
          description: Bad Request, Please provide email and Password
        '401':
          description: Unauthenticated Error, Invalid Credentials
        '500':
          description: Internal Server Error 
  
  /user/{userId}:
    get:
      summary: Get user by id of user
      parameters:
        - name: userId
          in: path
          required: true
          description: id of user
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              username:
                type: string
              email:
                type: string
                format: email
              profilePicture:
                type: string
              coverPicture:
                type: string
              followers:
                type: array
                items:  
                  type: string
              followings:
                type: array
                items:  
                  type: string
              isAdmin:
                type: boolean
              desc:
                type: string
                maxLength: 50
              city:
                type: string
                maxLength: 50
              from:
                type: string
                maxLength: 50
              relationship:
                type: integer
                enum: [1,2,3]
        '404': 
          description: Not Found. No job found with given jobId.
        '500':
          description: Internal Server Error

    put:
      summary: Update the user's details
      parameters:
        - name: userId
          in: path
          required: true
          description: id of user
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId: 
                  type: string
                desc:
                  type: string
                  maxLength: 50
              required:
                - userId
      responses:
        '200':
          description: OK
        '401':
          description: Authorization Error. User can update only their account.
        '404': 
          description: Not Found. No job found with given jobId.
        '500':
          description: Internal Server Error
      
